spring:
  profiles:
    active: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml
  jpa:
    show-sql: true
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: true
        ddl-auto: none
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: task
    properties:
      hibernate:
        id:
          new_generator_mappings: false