CREATE TYPE user_status AS ENUM ('ACTIVE', 'INACTIVE', 'SLEEPY', 'HIDDEN');

CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255) NOT NULL,
                       surname VARCHAR(255) NOT NULL,
                       birth_date DATE NOT NULL,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       active user_status NOT NULL,
                       created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                       version INTEGER NOT NULL
);

ALTER TABLE users ADD CONSTRAINT ck_users_email CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$');
ALTER TABLE users ADD CONSTRAINT ck_users_birth_date_past CHECK (birth_date < CURRENT_DATE);

CREATE TABLE payment_cards (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id BIGINT NOT NULL,
                               number VARCHAR(255) NOT NULL UNIQUE,
                               holder VARCHAR(255) NOT NULL,
                               expiration_date DATE NOT NULL,
                               active BOOLEAN NOT NULL,
                               created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                               updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                               version INTEGER NOT NULL,
                               CONSTRAINT fk_cards_user FOREIGN KEY (user_id) REFERENCES users(id)
);

ALTER TABLE payment_cards ADD CONSTRAINT ck_payment_cards_number_format CHECK (number ~ '^[0-9]{16}$');

CREATE INDEX idx_payment_cards_user_id ON payment_cards(user_id);

CREATE OR REPLACE FUNCTION set_initial_audit()
RETURNS TRIGGER AS $$
BEGIN
    NEW.created_at = CURRENT_TIMESTAMP;
    NEW.updated_at = CURRENT_TIMESTAMP;
    NEW.version = 0;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_audit()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    NEW.version = OLD.version + 1;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_users_insert ON users;
CREATE TRIGGER trg_users_insert
    BEFORE INSERT ON users
    FOR EACH ROW
    EXECUTE FUNCTION set_initial_audit();

DROP TRIGGER IF EXISTS trg_users_update ON users;
CREATE TRIGGER trg_users_update
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_audit();

DROP TRIGGER IF EXISTS trg_payment_cards_insert ON payment_cards;
CREATE TRIGGER trg_payment_cards_insert
    BEFORE INSERT ON payment_cards
    FOR EACH ROW
    EXECUTE FUNCTION set_initial_audit();

DROP TRIGGER IF EXISTS trg_payment_cards_update ON payment_cards;
CREATE TRIGGER trg_payment_cards_update
    BEFORE UPDATE ON payment_cards
    FOR EACH ROW
    EXECUTE FUNCTION update_audit();