CREATE TABLE payment_cards (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               user_id BIGINT NOT NULL,
                               number VARCHAR(255) NOT NULL UNIQUE,
                               holder VARCHAR(255) NOT NULL,
                               expiration_date DATE NOT NULL,
                               active BOOLEAN NOT NULL,
                               created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                               updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                               version INTEGER NOT NULL,
                               CONSTRAINT fk_cards_user FOREIGN KEY (user_id) REFERENCES users(id)
);

ALTER TABLE payment_cards ADD CONSTRAINT ck_payment_cards_number_format CHECK (number ~ '^[0-9]{16}$');